# Generated by Django 5.0.6 on 2024-05-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('ano', models.IntegerField(max_length=5000)),
                ('nota', models.FloatField(max_length=10)),
            ],
        ),
    ]
