# Generated by Django 5.0.6 on 2024-05-30 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ano',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1930), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='nota',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
