# Generated by Django 5.0.6 on 2024-05-30 21:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_game_ano_alter_game_nome_alter_game_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, unique=True)),
                ('Local', models.CharField(max_length=254)),
                ('fundacao', models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1930), django.core.validators.MaxValueValidator(2040)])),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='desenvolvedora',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.developer'),
            preserve_default=False,
        ),
    ]
